import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "@fontsource/be-vietnam-pro/latin-400.css";
import "@fontsource/be-vietnam-pro/latin-ext-400.css";
import "@fontsource/be-vietnam-pro/vietnamese-400.css";
import "@fontsource/be-vietnam-pro/latin-500.css";
import "@fontsource/be-vietnam-pro/latin-ext-500.css";
import "@fontsource/be-vietnam-pro/vietnamese-500.css";
import "@fontsource/be-vietnam-pro/latin-600.css";
import "@fontsource/be-vietnam-pro/latin-ext-600.css";
import "@fontsource/be-vietnam-pro/vietnamese-600.css";
import "@fontsource/be-vietnam-pro/latin-700.css";
import "@fontsource/be-vietnam-pro/latin-ext-700.css";
import "@fontsource/be-vietnam-pro/vietnamese-700.css";
import "@fontsource/be-vietnam-pro/latin-800.css";
import "@fontsource/be-vietnam-pro/latin-ext-800.css";
import "@fontsource/be-vietnam-pro/vietnamese-800.css";
import "@fontsource/space-mono/latin-400.css";
import "@fontsource/space-mono/latin-ext-400.css";
import "@fontsource/space-mono/vietnamese-400.css";
import "@fontsource/space-mono/latin-700.css";
import "@fontsource/space-mono/latin-ext-700.css";
import "@fontsource/space-mono/vietnamese-700.css";
import "@fontsource/lora/latin-400.css";
import "@fontsource/lora/latin-ext-400.css";
import "@fontsource/lora/vietnamese-400.css";
import "@fontsource/lora/latin-400-italic.css";
import "@fontsource/lora/latin-ext-400-italic.css";
import "@fontsource/lora/vietnamese-400-italic.css";
import "@fontsource/lora/latin-600.css";
import "@fontsource/lora/latin-ext-600.css";
import "@fontsource/lora/vietnamese-600.css";
import "@fontsource/lora/latin-600-italic.css";
import "@fontsource/lora/latin-ext-600-italic.css";
import "@fontsource/lora/vietnamese-600-italic.css";
import "@fontsource/lora/latin-700.css";
import "@fontsource/lora/latin-ext-700.css";
import "@fontsource/lora/vietnamese-700.css";
import "@fontsource/lora/latin-700-italic.css";
import "@fontsource/lora/latin-ext-700-italic.css";
import "@fontsource/lora/vietnamese-700-italic.css";
import "./styles.css";
import "./game-ui.css";
import "./landing.css";
ReactDOM.createRoot(document.getElementById("root")!).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
